import { useEffect, useState } from 'react';
import { catalogDataService } from '@/domains/catalog/services/catalog-data.service';
import type { CategoryRow } from '@/domains/catalog/types/catalog.db.types';
import { slugify } from '@/lib/slugify';
import { toast } from 'sonner';

const initialForm = { slug: '', name: '', description: '' };

export function AdminCategoriesPage() {
  const [items, setItems] = useState<CategoryRow[]>([]);
  const [form, setForm] = useState(initialForm);
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(true);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const load = async () => {
    setLoading(true);
    setError('');
    try {
      setItems(await catalogDataService.getCategoriesAdmin());
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Error cargando categorías';
      setError(message);
      toast.error(message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void load();
  }, []);

  const onCreate = async (event: React.FormEvent) => {
    event.preventDefault();
    try {
      await catalogDataService.createCategory(form);
      setForm(initialForm);
      setIsSlugAutoGenerated(true);
      toast.success('Categoría creada correctamente');
      await load();
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Error creando categoría';
      setError(message);
      toast.error(message);
    }
  };

  const onDelete = async (id: string) => {
    try {
      await catalogDataService.deleteCategory(id);
      toast.success('Eliminado correctamente');
      await load();
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Error eliminando categoría';
      setError(message);
      toast.error(message);
    }
  };

  return (
    <section className="space-y-6">
      <header>
        <h1 className="text-2xl font-bold text-slate-900">Categorías</h1>
        <p className="text-slate-600">CRUD básico conectado a Supabase.</p>
      </header>

      {error && <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-2 text-sm text-red-700">{error}</div>}

      <form onSubmit={onCreate} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4">
        <input
          value={form.slug}
          onChange={(e) => setForm((p) => ({ ...p, slug: e.target.value }))}
          placeholder="slug"
          className={`rounded border px-3 py-2 ${isSlugAutoGenerated ? 'border-blue-200 bg-blue-50 text-blue-700' : ''}`}
          readOnly={isSlugAutoGenerated}
          required
        />
        <button
          type="button"
          onClick={() => setIsSlugAutoGenerated(false)}
          className="rounded border border-blue-200 px-3 py-2 text-xs font-medium uppercase tracking-wide text-blue-700"
        >
          {isSlugAutoGenerated ? 'Auto-generado (clic para editar)' : 'Slug editable'}
        </button>
        <input
          value={form.name}
          onChange={(e) =>
            setForm((p) => ({
              ...p,
              name: e.target.value,
              slug: isSlugAutoGenerated ? slugify(e.target.value) : p.slug,
            }))
          }
          placeholder="nombre"
          className="rounded border px-3 py-2"
          required
        />
        <input value={form.description} onChange={(e) => setForm((p) => ({ ...p, description: e.target.value }))} placeholder="descripción" className="rounded border px-3 py-2" />
        <button type="submit" className="rounded bg-slate-900 px-4 py-2 text-white">Crear</button>
      </form>

      <div className="overflow-x-auto rounded-xl border bg-white">
        <table className="w-full text-sm">
          <thead className="bg-slate-50 text-slate-700">
            <tr>
              <th className="px-3 py-2 text-left">Slug</th>
              <th className="px-3 py-2 text-left">Nombre</th>
              <th className="px-3 py-2 text-left">Descripción</th>
              <th className="px-3 py-2 text-left">Acciones</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td className="px-3 py-3" colSpan={4}>Cargando...</td></tr>
            ) : (
              items.map((item) => (
                <tr key={item.id} className="border-t">
                  <td className="px-3 py-2">{item.slug}</td>
                  <td className="px-3 py-2">{item.name}</td>
                  <td className="px-3 py-2">{item.description}</td>
                  <td className="px-3 py-2">
                    <button onClick={() => void onDelete(item.id)} className="rounded border px-2 py-1 text-red-600">Eliminar</button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
}
