import { useCallback, useEffect, useState } from 'react';
import { catalogDataService } from '@/domains/catalog/services/catalog-data.service';
import type { CategoryRow, ProductRow } from '@/domains/catalog/types/catalog.db.types';
import { supabase } from '@/integrations/supabase/client';
import { optimizeImageBeforeUpload } from '@/lib/imageOptimizer';
import { slugify } from '@/lib/slugify';
import { toast } from 'sonner';

const initialForm = {
  category_id: '',
  slug: '',
  name: '',
  description: '',
  price: 0,
  image_url: '',
  unit: 'unidad' as const,
  min_quantity: 1,
};
const PAGE_SIZE = 20;

export function AdminProductsPage() {
  const [items, setItems] = useState<ProductRow[]>([]);
  const [totalItems, setTotalItems] = useState(0);
  const [categories, setCategories] = useState<CategoryRow[]>([]);
  const [form, setForm] = useState(initialForm);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreviewUrl, setImagePreviewUrl] = useState<string | null>(null);
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(true);
  const [page, setPage] = useState(1);
  const [categoryFilter, setCategoryFilter] = useState('');
  const [searchFilter, setSearchFilter] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const [categoriesRes, productsRes] = await Promise.all([
        catalogDataService.getCategoriesAdmin(),
        catalogDataService.getProductsAdminPage({
          limit: PAGE_SIZE,
          offset: (page - 1) * PAGE_SIZE,
          filters: {
            categoryId: categoryFilter || undefined,
            search: searchFilter || undefined,
          },
        }),
      ]);
      setCategories(categoriesRes);
      setItems(productsRes.items);
      setTotalItems(productsRes.total);

      if (!form.category_id && categoriesRes[0]) {
        setForm((prev) => ({ ...prev, category_id: categoriesRes[0].id }));
      }
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Error cargando productos';
      setError(message);
      toast.error(message);
    } finally {
      setLoading(false);
    }
  }, [categoryFilter, form.category_id, page, searchFilter]);

  useEffect(() => {
    void load();
  }, [load]);

  useEffect(() => () => {
    if (imagePreviewUrl) {
      URL.revokeObjectURL(imagePreviewUrl);
    }
  }, [imagePreviewUrl]);

  const onCreate = async (event: React.FormEvent) => {
    event.preventDefault();

    try {
      let imageUrl = '';

      // 🔥 optimizar y subir imagen automáticamente
      if (imageFile) {
        const optimizedImage = await optimizeImageBeforeUpload(imageFile);
        const sanitizedName = imageFile.name.replace(/\.[^/.]+$/, '');
        const fileName = `${Date.now()}-${sanitizedName}.webp`;

        const { error: uploadError } = await supabase.storage
          .from('images')
          .upload(fileName, optimizedImage, {
            contentType: 'image/webp',
            upsert: false,
          });

        if (uploadError) throw uploadError;

        const { data } = supabase.storage
          .from('images')
          .getPublicUrl(fileName);

        imageUrl = data.publicUrl;
      }

      await catalogDataService.createProduct({
        ...form,
        image_url: imageUrl,
      });
      toast.success('Producto creado correctamente');

      setForm((prev) => ({
        ...initialForm,
        category_id: prev.category_id,
      }));

      setIsSlugAutoGenerated(true);
      setImageFile(null);
      if (imagePreviewUrl) {
        URL.revokeObjectURL(imagePreviewUrl);
      }
      setImagePreviewUrl(null);

      if (page === 1) {
        await load();
      } else {
        setPage(1);
      }
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Error creando producto';
      setError(message);
      toast.error(message);
    }
  };

  const onDelete = async (id: string) => {
    try {
      await catalogDataService.deleteProduct(id);
      toast.success('Eliminado correctamente');
      if (items.length === 1 && page > 1) {
        setPage((prev) => prev - 1);
        return;
      }
      if (page === 1) {
        await load();
      } else {
        setPage(1);
      }
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Error eliminando producto';
      setError(message);
      toast.error(message);
    }
  };

  const categoryNameById = Object.fromEntries(
    categories.map((category) => [category.id, category.name])
  );
  const totalPages = Math.max(1, Math.ceil(totalItems / PAGE_SIZE));
  const firstItemIndex = totalItems === 0 ? 0 : (page - 1) * PAGE_SIZE + 1;
  const lastItemIndex = Math.min(page * PAGE_SIZE, totalItems);

  return (
    <section className="space-y-6">
      <header>
        <h1 className="text-2xl font-bold text-slate-900">Productos</h1>
        <p className="text-slate-600">CRUD básico conectado a Supabase.</p>
      </header>

      {error && (
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-2 text-sm text-red-700">
          {error}
        </div>
      )}

      <form
        onSubmit={onCreate}
        className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4"
      >
        <select
          value={form.category_id}
          onChange={(e) =>
            setForm((p) => ({ ...p, category_id: e.target.value }))
          }
          className="rounded border px-3 py-2"
          required
        >
          {categories.map((category) => (
            <option key={category.id} value={category.id}>
              {category.name}
            </option>
          ))}
        </select>

        <input
          value={form.slug}
          onChange={(e) =>
            setForm((p) => ({ ...p, slug: e.target.value }))
          }
          placeholder="slug"
          className={`rounded border px-3 py-2 ${
            isSlugAutoGenerated
              ? 'border-blue-200 bg-blue-50 text-blue-700'
              : ''
          }`}
          readOnly={isSlugAutoGenerated}
          required
        />
        <button
          type="button"
          onClick={() => setIsSlugAutoGenerated(false)}
          className="rounded border border-blue-200 px-3 py-2 text-xs font-medium uppercase tracking-wide text-blue-700"
        >
          {isSlugAutoGenerated ? 'Auto-generado (clic para editar)' : 'Slug editable'}
        </button>

        <input
          value={form.name}
          onChange={(e) =>
            setForm((p) => ({
              ...p,
              name: e.target.value,
              slug: isSlugAutoGenerated ? slugify(e.target.value) : p.slug,
            }))
          }
          placeholder="nombre"
          className="rounded border px-3 py-2"
          required
        />

        <input
          type="number"
          value={form.price}
          onChange={(e) =>
            setForm((p) => ({ ...p, price: Number(e.target.value) }))
          }
          placeholder="precio"
          className="rounded border px-3 py-2"
          required
        />

        <input
          value={form.description}
          onChange={(e) =>
            setForm((p) => ({ ...p, description: e.target.value }))
          }
          placeholder="descripción"
          className="rounded border px-3 py-2 md:col-span-2"
        />

        {/* 🔥 SOLO SUBIR IMAGEN DESDE PC */}
        <input
          type="file"
          accept="image/*"
          onChange={(e) => {
            const selectedFile = e.target.files?.[0] || null;
            setImageFile(selectedFile);

            if (imagePreviewUrl) {
              URL.revokeObjectURL(imagePreviewUrl);
            }

            setImagePreviewUrl(selectedFile ? URL.createObjectURL(selectedFile) : null);
          }}
          className="rounded border px-3 py-2"
        />

        <select
          value={form.unit}
          onChange={(e) =>
            setForm((p) => ({
              ...p,
              unit: e.target.value as typeof form.unit,
            }))
          }
          className="rounded border px-3 py-2"
        >
          <option value="unidad">unidad</option>
          <option value="m2">m2</option>
          <option value="kg">kg</option>
        </select>

        {imagePreviewUrl && (
          <div className="md:col-span-2">
            <p className="mb-2 text-xs font-medium uppercase tracking-wide text-slate-500">
              Vista previa
            </p>
            <img
              src={imagePreviewUrl}
              alt="Vista previa de imagen seleccionada"
              className="h-24 w-24 rounded border object-cover"
            />
          </div>
        )}

        <input
          type="number"
          value={form.min_quantity}
          onChange={(e) =>
            setForm((p) => ({
              ...p,
              min_quantity: Number(e.target.value),
            }))
          }
          placeholder="mínimo"
          className="rounded border px-3 py-2"
        />

        <button
          type="submit"
          className="rounded bg-slate-900 px-4 py-2 text-white"
        >
          Crear
        </button>
      </form>

      <div className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4">
        <select
          value={categoryFilter}
          onChange={(event) => {
            setCategoryFilter(event.target.value);
            setPage(1);
          }}
          className="rounded border px-3 py-2"
        >
          <option value="">Todas las categorías</option>
          {categories.map((category) => (
            <option key={category.id} value={category.id}>
              {category.name}
            </option>
          ))}
        </select>
        <input
          value={searchFilter}
          onChange={(event) => {
            setSearchFilter(event.target.value);
            setPage(1);
          }}
          placeholder="Buscar por nombre"
          className="rounded border px-3 py-2 md:col-span-2"
        />
        <p className="flex items-center text-sm text-slate-600">
          {firstItemIndex}-{lastItemIndex} de {totalItems} productos
        </p>
      </div>

      <div className="overflow-x-auto rounded-xl border bg-white">
        <table className="w-full text-sm">
          <thead className="bg-slate-50 text-slate-700">
            <tr>
              <th className="px-3 py-2 text-left">Nombre</th>
              <th className="px-3 py-2 text-left">Categoría</th>
              <th className="px-3 py-2 text-left">Precio</th>
              <th className="px-3 py-2 text-left">Unidad</th>
              <th className="px-3 py-2 text-left">Acciones</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td className="px-3 py-3" colSpan={5}>
                  Cargando...
                </td>
              </tr>
            ) : (
              items.map((item) => (
                <tr key={item.id} className="border-t">
                  <td className="px-3 py-2">{item.name}</td>
                  <td className="px-3 py-2">
                    {categoryNameById[item.category_id] || '-'}
                  </td>
                  <td className="px-3 py-2">{item.price}</td>
                  <td className="px-3 py-2">{item.unit}</td>
                  <td className="px-3 py-2">
                    <button
                      onClick={() => void onDelete(item.id)}
                      className="rounded border px-2 py-1 text-red-600"
                    >
                      Eliminar
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div className="flex items-center justify-end gap-2">
        <button
          type="button"
          onClick={() => setPage((prev) => Math.max(1, prev - 1))}
          disabled={page === 1}
          className="rounded border px-3 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-50"
        >
          Anterior
        </button>
        <span className="text-sm text-slate-600">Página {page} de {totalPages}</span>
        <button
          type="button"
          onClick={() => setPage((prev) => Math.min(totalPages, prev + 1))}
          disabled={page >= totalPages}
          className="rounded border px-3 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-50"
        >
          Siguiente
        </button>
      </div>
    </section>
  );
}
