import { useCallback, useEffect, useMemo, useState } from 'react';
import { catalogDataService } from '@/domains/catalog/services/catalog-data.service';
import type { CategoryRow, ProductRow } from '@/domains/catalog/types/catalog.db.types';
import { supabase } from '@/integrations/supabase/client';
import { optimizeImageBeforeUpload } from '@/lib/imageOptimizer';
import { slugify } from '@/lib/slugify';
import { toast } from 'sonner';

const initialForm = {
  category_id: '',
  slug: '',
  name: '',
  description: '',
  price: 0,
  image_url: '',
  unit: 'unidad' as const,
  min_quantity: 1,
};
const PAGE_SIZE = 20;
const MEDIA_PAGE_SIZE = 18;

type MediaImage = {
  name: string;
  url: string;
};

export function AdminProductsPage() {
  const [items, setItems] = useState<ProductRow[]>([]);
  const [totalItems, setTotalItems] = useState(0);
  const [categories, setCategories] = useState<CategoryRow[]>([]);
  const [form, setForm] = useState(initialForm);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreviewUrl, setImagePreviewUrl] = useState<string | null>(null);
  const [mediaLibrary, setMediaLibrary] = useState<MediaImage[]>([]);
  const [loadingMedia, setLoadingMedia] = useState(false);
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(true);
  const [page, setPage] = useState(1);
  const [categoryFilter, setCategoryFilter] = useState('');
  const [searchFilter, setSearchFilter] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const categoryNameById = useMemo(
    () => Object.fromEntries(
      categories.map((category) => [category.id, category.name])
    ),
    [categories]
  );

  const formErrors = useMemo(() => {
    const errors: Record<string, string> = {};
    if (!form.category_id) {
      errors.category_id = 'Selecciona una categoría';
    }
    if (!form.name.trim()) {
      errors.name = 'El nombre es obligatorio';
    } else if (form.name.trim().length < 3) {
      errors.name = 'El nombre debe tener al menos 3 caracteres';
    }
    if (!form.slug.trim()) {
      errors.slug = 'El slug es obligatorio';
    } else if (!/^[a-z0-9-]+$/.test(form.slug.trim())) {
      errors.slug = 'Usa solo minúsculas, números y guiones';
    }
    if (!Number.isFinite(form.price) || form.price <= 0) {
      errors.price = 'El precio debe ser mayor que 0';
    }
    if (!Number.isFinite(form.min_quantity) || form.min_quantity < 1) {
      errors.min_quantity = 'La cantidad mínima debe ser 1 o mayor';
    }
    return errors;
  }, [form]);

  const isFormValid = Object.keys(formErrors).length === 0;

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const [categoriesRes, productsRes] = await Promise.all([
        catalogDataService.getCategoriesAdmin(),
        catalogDataService.getProductsAdminPage({
          limit: PAGE_SIZE,
          offset: (page - 1) * PAGE_SIZE,
          filters: {
            categoryId: categoryFilter || undefined,
            search: searchFilter || undefined,
          },
        }),
      ]);
      setCategories(categoriesRes);
      setItems(productsRes.items);
      setTotalItems(productsRes.total);

      if (!form.category_id && categoriesRes[0]) {
        setForm((prev) => ({ ...prev, category_id: categoriesRes[0].id }));
      }
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Error cargando productos';
      setError(message);
      toast.error(message);
    } finally {
      setLoading(false);
    }
  }, [categoryFilter, form.category_id, page, searchFilter]);

  const loadMediaLibrary = useCallback(async () => {
    setLoadingMedia(true);
    try {
      const { data, error: listError } = await supabase.storage
        .from('images')
        .list('', {
          limit: MEDIA_PAGE_SIZE,
          offset: 0,
          sortBy: { column: 'created_at', order: 'desc' },
        });

      if (listError) throw listError;

      const parsedMedia = (data || [])
        .filter((file) => Boolean(file.name))
        .map((file) => {
          const { data: publicData } = supabase.storage
            .from('images')
            .getPublicUrl(file.name);
          return {
            name: file.name,
            url: publicData.publicUrl,
          };
        });

      setMediaLibrary(parsedMedia);
    } catch (e) {
      const message = e instanceof Error ? e.message : 'No se pudo cargar la librería de medios';
      toast.error(message);
    } finally {
      setLoadingMedia(false);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  useEffect(() => {
    void loadMediaLibrary();
  }, [loadMediaLibrary]);

  useEffect(() => () => {
    if (imagePreviewUrl) {
      URL.revokeObjectURL(imagePreviewUrl);
    }
  }, [imagePreviewUrl]);

  const onCreate = async (event: React.FormEvent) => {
    event.preventDefault();

    try {
      let imageUrl = form.image_url;

      // 🔥 optimizar y subir imagen automáticamente
      if (imageFile) {
        const optimizedImage = await optimizeImageBeforeUpload(imageFile);
        const sanitizedName = imageFile.name.replace(/\.[^/.]+$/, '');
        const fileName = `${Date.now()}-${sanitizedName}.webp`;

        const { error: uploadError } = await supabase.storage
          .from('images')
          .upload(fileName, optimizedImage, {
            contentType: 'image/webp',
            upsert: false,
          });

        if (uploadError) throw uploadError;

        const { data } = supabase.storage
          .from('images')
          .getPublicUrl(fileName);

        imageUrl = data.publicUrl;
      }

      await catalogDataService.createProduct({
        ...form,
        image_url: imageUrl,
      });
      toast.success('Producto creado correctamente');

      setForm((prev) => ({
        ...initialForm,
        category_id: prev.category_id,
      }));

      setIsSlugAutoGenerated(true);
      setImageFile(null);
      if (imagePreviewUrl) {
        URL.revokeObjectURL(imagePreviewUrl);
      }
      setImagePreviewUrl(null);

      if (page === 1) {
        await load();
      } else {
        setPage(1);
      }
      await loadMediaLibrary();
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Error creando producto';
      setError(message);
      toast.error(message);
    }
  };

  const onDelete = async (id: string) => {
    try {
      await catalogDataService.deleteProduct(id);
      toast.success('Eliminado correctamente');
      if (items.length === 1 && page > 1) {
        setPage((prev) => prev - 1);
        return;
      }
      if (page === 1) {
        await load();
      } else {
        setPage(1);
      }
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Error eliminando producto';
      setError(message);
      toast.error(message);
    }
  };

  const totalPages = Math.max(1, Math.ceil(totalItems / PAGE_SIZE));
  const firstItemIndex = totalItems === 0 ? 0 : (page - 1) * PAGE_SIZE + 1;
  const lastItemIndex = Math.min(page * PAGE_SIZE, totalItems);

  return (
    <section className="space-y-6">
      <header>
        <h1 className="text-2xl font-bold text-slate-900">Productos</h1>
        <p className="text-slate-600">CRUD básico conectado a Supabase.</p>
      </header>

      {error && (
        <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-2 text-sm text-red-700">
          {error}
        </div>
      )}

      <form
        onSubmit={onCreate}
        className="grid gap-4 lg:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]"
      >
        <div className="space-y-4">
          <section className="rounded-xl border bg-white p-4">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
              Información básica
            </h2>
            <div className="mt-4 grid gap-4 md:grid-cols-2">
              <label className="space-y-1 text-sm text-slate-700">
                <span className="font-medium">Categoría</span>
                <select
                  value={form.category_id}
                  onChange={(e) =>
                    setForm((p) => ({ ...p, category_id: e.target.value }))
                  }
                  className="w-full rounded border px-3 py-2"
                  required
                >
                  {categories.map((category) => (
                    <option key={category.id} value={category.id}>
                      {category.name}
                    </option>
                  ))}
                </select>
                {formErrors.category_id && (
                  <p className="text-xs text-red-600">{formErrors.category_id}</p>
                )}
              </label>

              <label className="space-y-1 text-sm text-slate-700">
                <span className="font-medium">Nombre del producto</span>
                <input
                  value={form.name}
                  onChange={(e) =>
                    setForm((p) => ({
                      ...p,
                      name: e.target.value,
                      slug: isSlugAutoGenerated ? slugify(e.target.value) : p.slug,
                    }))
                  }
                  placeholder="Ej: Cesped Esmeralda"
                  className="w-full rounded border px-3 py-2"
                  required
                />
                {formErrors.name && (
                  <p className="text-xs text-red-600">{formErrors.name}</p>
                )}
              </label>

              <label className="space-y-1 text-sm text-slate-700 md:col-span-2">
                <span className="flex items-center justify-between gap-2 font-medium">
                  Descripción
                  <button
                    type="button"
                    onClick={() =>
                      setForm((prev) => ({
                        ...prev,
                        description: `Producto ${prev.name || 'destacado'} de ${categoryNameById[prev.category_id] || 'catálogo'} con calidad premium y entrega rápida.`,
                      }))
                    }
                    className="rounded border px-2 py-1 text-[11px] uppercase tracking-wide text-slate-600"
                  >
                    Autocompletar
                  </button>
                </span>
                <input
                  value={form.description}
                  onChange={(e) =>
                    setForm((p) => ({ ...p, description: e.target.value }))
                  }
                  placeholder="Describe beneficios, uso y diferenciadores"
                  className="w-full rounded border px-3 py-2"
                />
              </label>
            </div>
          </section>

          <section className="rounded-xl border bg-white p-4">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
              Precio y reglas de compra
            </h2>
            <div className="mt-4 grid gap-4 md:grid-cols-3">
              <label className="space-y-1 text-sm text-slate-700">
                <span className="font-medium">Precio</span>
                <input
                  type="number"
                  value={form.price}
                  onChange={(e) =>
                    setForm((p) => ({ ...p, price: Number(e.target.value) }))
                  }
                  placeholder="0"
                  className="w-full rounded border px-3 py-2"
                  required
                />
                {formErrors.price && (
                  <p className="text-xs text-red-600">{formErrors.price}</p>
                )}
              </label>

              <label className="space-y-1 text-sm text-slate-700">
                <span className="font-medium">Unidad</span>
                <select
                  value={form.unit}
                  onChange={(e) =>
                    setForm((p) => ({
                      ...p,
                      unit: e.target.value as typeof form.unit,
                    }))
                  }
                  className="w-full rounded border px-3 py-2"
                >
                  <option value="unidad">unidad</option>
                  <option value="m2">m2</option>
                  <option value="kg">kg</option>
                </select>
              </label>

              <label className="space-y-1 text-sm text-slate-700">
                <span className="font-medium">Cantidad mínima</span>
                <input
                  type="number"
                  value={form.min_quantity}
                  onChange={(e) =>
                    setForm((p) => ({
                      ...p,
                      min_quantity: Number(e.target.value),
                    }))
                  }
                  placeholder="1"
                  className="w-full rounded border px-3 py-2"
                />
                {formErrors.min_quantity && (
                  <p className="text-xs text-red-600">{formErrors.min_quantity}</p>
                )}
              </label>
            </div>
          </section>

          <section className="rounded-xl border bg-white p-4">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
              SEO y URL
            </h2>
            <div className="mt-4 grid gap-4 md:grid-cols-[minmax(0,1fr)_auto]">
              <label className="space-y-1 text-sm text-slate-700">
                <span className="font-medium">Slug</span>
                <input
                  value={form.slug}
                  onChange={(e) =>
                    setForm((p) => ({ ...p, slug: e.target.value }))
                  }
                  placeholder="slug-del-producto"
                  className={`w-full rounded border px-3 py-2 ${
                    isSlugAutoGenerated
                      ? 'border-blue-200 bg-blue-50 text-blue-700'
                      : ''
                  }`}
                  readOnly={isSlugAutoGenerated}
                  required
                />
                {formErrors.slug && (
                  <p className="text-xs text-red-600">{formErrors.slug}</p>
                )}
              </label>

              <div className="flex gap-2 self-end">
                <button
                  type="button"
                  onClick={() => setIsSlugAutoGenerated(false)}
                  className="rounded border border-blue-200 px-3 py-2 text-xs font-medium uppercase tracking-wide text-blue-700"
                >
                  {isSlugAutoGenerated ? 'Editar slug' : 'Slug editable'}
                </button>
                <button
                  type="button"
                  onClick={() =>
                    setForm((prev) => ({
                      ...prev,
                      slug: slugify(prev.name),
                    }))
                  }
                  className="rounded border px-3 py-2 text-xs font-medium uppercase tracking-wide text-slate-700"
                >
                  Regenerar
                </button>
              </div>
            </div>
          </section>

          <section className="rounded-xl border bg-white p-4">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
              Imagen principal
            </h2>
            <div className="mt-4 space-y-2">
              <label className="space-y-1 text-sm text-slate-700">
                <span className="font-medium">Archivo</span>
                <input
                  type="file"
                  accept="image/*"
                  onChange={(e) => {
                    const selectedFile = e.target.files?.[0] || null;
                    setImageFile(selectedFile);
                    setForm((prev) => ({ ...prev, image_url: '' }));

                    if (imagePreviewUrl) {
                      URL.revokeObjectURL(imagePreviewUrl);
                    }

                    setImagePreviewUrl(selectedFile ? URL.createObjectURL(selectedFile) : null);
                  }}
                  className="w-full rounded border px-3 py-2"
                />
              </label>
              {imageFile && (
                <p className="text-xs text-emerald-700">
                  Archivo seleccionado: {imageFile.name}
                </p>
              )}
              <p className="text-xs text-slate-500">
                Formatos aceptados: cualquier imagen compatible con navegador.
              </p>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
                    Biblioteca de imágenes
                  </p>
                  <button
                    type="button"
                    onClick={() => void loadMediaLibrary()}
                    className="rounded border px-2 py-1 text-xs text-slate-600"
                  >
                    Actualizar
                  </button>
                </div>
                {loadingMedia ? (
                  <p className="text-xs text-slate-500">Cargando imágenes...</p>
                ) : mediaLibrary.length === 0 ? (
                  <p className="text-xs text-slate-500">No hay imágenes en la librería.</p>
                ) : (
                  <div className="grid grid-cols-3 gap-2">
                    {mediaLibrary.map((media) => {
                      const isSelected = form.image_url === media.url && !imageFile;
                      return (
                        <button
                          key={media.name}
                          type="button"
                          onClick={() => {
                            if (imagePreviewUrl) {
                              URL.revokeObjectURL(imagePreviewUrl);
                            }
                            setImageFile(null);
                            setImagePreviewUrl(media.url);
                            setForm((prev) => ({ ...prev, image_url: media.url }));
                          }}
                          className={`overflow-hidden rounded border ${
                            isSelected ? 'border-slate-900 ring-1 ring-slate-900' : 'border-slate-200'
                          }`}
                        >
                          <img
                            src={media.url}
                            alt={media.name}
                            className="h-16 w-full object-cover"
                          />
                        </button>
                      );
                    })}
                  </div>
                )}
              </div>
            </div>
          </section>
        </div>

        <aside className="h-fit space-y-4 rounded-xl border bg-white p-4">
          <div>
            <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
              Vista previa rápida
            </h2>
            <p className="mt-1 text-xs text-slate-500">
              Así se verá el producto antes de guardarlo.
            </p>
          </div>

          <div className="overflow-hidden rounded-lg border bg-slate-50">
            {imagePreviewUrl ? (
              <img
                src={imagePreviewUrl}
                alt="Vista previa de imagen seleccionada"
                className="h-44 w-full object-cover"
              />
            ) : (
              <div className="flex h-44 items-center justify-center text-sm text-slate-400">
                Sin imagen seleccionada
              </div>
            )}
            <div className="space-y-2 p-3">
              <p className="line-clamp-1 font-medium text-slate-900">
                {form.name || 'Nombre del producto'}
              </p>
              <p className="text-sm text-slate-600">
                {form.description || 'La descripción del producto aparecerá aquí.'}
              </p>
              <p className="text-sm font-semibold text-slate-900">
                ${Number.isFinite(form.price) ? form.price : 0} / {form.unit}
              </p>
              <p className="text-xs text-slate-500">
                Mínimo de compra: {form.min_quantity || 1}
              </p>
            </div>
          </div>

          <button
            type="submit"
            disabled={!isFormValid}
            className="w-full rounded bg-slate-900 px-4 py-2 text-white"
          >
            Guardar y crear producto
          </button>
          {!isFormValid && (
            <p className="text-xs text-amber-700">
              Completa los campos obligatorios para guardar.
            </p>
          )}
        </aside>
      </form>

      <div className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4">
        <select
          value={categoryFilter}
          onChange={(event) => {
            setCategoryFilter(event.target.value);
            setPage(1);
          }}
          className="rounded border px-3 py-2"
        >
          <option value="">Todas las categorías</option>
          {categories.map((category) => (
            <option key={category.id} value={category.id}>
              {category.name}
            </option>
          ))}
        </select>
        <input
          value={searchFilter}
          onChange={(event) => {
            setSearchFilter(event.target.value);
            setPage(1);
          }}
          placeholder="Buscar por nombre"
          className="rounded border px-3 py-2 md:col-span-2"
        />
        <p className="flex items-center text-sm text-slate-600">
          {firstItemIndex}-{lastItemIndex} de {totalItems} productos
        </p>
      </div>

      <div className="overflow-x-auto rounded-xl border bg-white">
        <table className="w-full text-sm">
          <thead className="bg-slate-50 text-slate-700">
            <tr>
              <th className="px-3 py-2 text-left">Nombre</th>
              <th className="px-3 py-2 text-left">Categoría</th>
              <th className="px-3 py-2 text-left">Precio</th>
              <th className="px-3 py-2 text-left">Unidad</th>
              <th className="px-3 py-2 text-left">Acciones</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td className="px-3 py-3" colSpan={5}>
                  Cargando...
                </td>
              </tr>
            ) : (
              items.map((item) => (
                <tr key={item.id} className="border-t">
                  <td className="px-3 py-2">{item.name}</td>
                  <td className="px-3 py-2">
                    {categoryNameById[item.category_id] || '-'}
                  </td>
                  <td className="px-3 py-2">{item.price}</td>
                  <td className="px-3 py-2">{item.unit}</td>
                  <td className="px-3 py-2">
                    <button
                      onClick={() => void onDelete(item.id)}
                      className="rounded border px-2 py-1 text-red-600"
                    >
                      Eliminar
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div className="flex items-center justify-end gap-2">
        <button
          type="button"
          onClick={() => setPage((prev) => Math.max(1, prev - 1))}
          disabled={page === 1}
          className="rounded border px-3 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-50"
        >
          Anterior
        </button>
        <span className="text-sm text-slate-600">Página {page} de {totalPages}</span>
        <button
          type="button"
          onClick={() => setPage((prev) => Math.min(totalPages, prev + 1))}
          disabled={page >= totalPages}
          className="rounded border px-3 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-50"
        >
          Siguiente
        </button>
      </div>
    </section>
  );
}
